export const PAIRS = [
  // LARGE CAP
  { s: 'BTCUSDT',    mcap: 1300000, type: 'spot' },
  { s: 'ETHUSDT',    mcap: 420000,  type: 'spot' },
  { s: 'BNBUSDT',    mcap: 89000,   type: 'spot' },
  { s: 'SOLUSDT',    mcap: 75000,   type: 'spot' },
  { s: 'XRPUSDT',    mcap: 32000,   type: 'spot' },
  { s: 'DOGEUSDT',   mcap: 26000,   type: 'spot' },
  { s: 'ADAUSDT',    mcap: 21500,   type: 'spot' },
  { s: 'AVAXUSDT',   mcap: 17000,   type: 'spot' },
  { s: 'TONUSDT',    mcap: 17200,   type: 'spot' },
  { s: 'DOTUSDT',    mcap: 12000,   type: 'spot' },
  { s: 'LINKUSDT',   mcap: 11000,   type: 'spot' },
  { s: 'TRXUSDT',    mcap: 11000,   type: 'spot' },
  { s: 'XLMUSDT',    mcap: 9800,    type: 'spot' },
  { s: 'SHIBUSDT',   mcap: 9700,    type: 'spot' },
  { s: 'UNIUSDT',    mcap: 9600,    type: 'spot' },
  { s: 'MATICUSDT',  mcap: 8700,    type: 'spot' },
  { s: 'NEARUSDT',   mcap: 8100,    type: 'spot' },
  { s: 'LTCUSDT',    mcap: 7300,    type: 'spot' },
  { s: 'BCHUSDT',    mcap: 7100,    type: 'spot' },
  { s: 'ICPUSDT',    mcap: 6900,    type: 'spot' },
  { s: 'APTUSDT',    mcap: 6200,    type: 'spot' },
  { s: 'ARBUSDT',    mcap: 5900,    type: 'spot' },
  { s: 'PEPEUSDT',   mcap: 5400,    type: 'spot' },
  { s: 'SUIUSDT',    mcap: 4800,    type: 'spot' },
  { s: 'ETCUSDT',    mcap: 4100,    type: 'spot' },
  { s: 'HBARUSDT',   mcap: 4200,    type: 'spot' },
  // MID CAP
  { s: 'INJUSDT',    mcap: 3600,    type: 'spot' },
  { s: 'OPUSDT',     mcap: 3200,    type: 'spot' },
  { s: 'TAOUSDT',    mcap: 3200,    type: 'spot' },
  { s: 'STXUSDT',    mcap: 3100,    type: 'spot' },
  { s: 'RENDERUSDT', mcap: 3800,    type: 'spot' },
  { s: 'WIFUSDT',    mcap: 3800,    type: 'spot' },
  { s: 'FETUSDT',    mcap: 2600,    type: 'spot' },
  { s: 'LDOUSDT',    mcap: 2600,    type: 'spot' },
  { s: 'FTMUSDT',    mcap: 2300,    type: 'spot' },
  { s: 'BONKUSDT',   mcap: 2100,    type: 'spot' },
  { s: 'TIAUSDT',    mcap: 2100,    type: 'spot' },
  { s: 'WLDUSDT',    mcap: 2100,    type: 'spot' },
  { s: 'MKRUSDT',    mcap: 2200,    type: 'spot' },
  { s: 'AAVEUSDT',   mcap: 2700,    type: 'spot' },
  { s: 'FLOKIUSDT',  mcap: 2600,    type: 'spot' },
  { s: 'KASUSDT',    mcap: 2800,    type: 'spot' },
  { s: 'ORDIUSDT',   mcap: 1800,    type: 'spot' },
  { s: 'ENAUSDT',    mcap: 1350,    type: 'spot' },
  { s: 'JUPUSDT',    mcap: 1650,    type: 'spot' },
  { s: 'GALAUSDT',   mcap: 1700,    type: 'spot' },
  { s: 'ALGOUSDT',   mcap: 1700,    type: 'spot' },
  { s: 'VETUSDT',    mcap: 3500,    type: 'spot' },
  { s: 'ARUSDT',     mcap: 1600,    type: 'spot' },
  { s: 'SANDUSDT',   mcap: 1300,    type: 'spot' },
  { s: 'QNTUSDT',    mcap: 1400,    type: 'spot' },
  { s: 'AXSUSDT',    mcap: 1500,    type: 'spot' },
  { s: 'ATOMUSDT',   mcap: 2400,    type: 'spot' },
  { s: 'IMXUSDT',    mcap: 1500,    type: 'spot' },
  { s: 'ONDOUSDT',   mcap: 1400,    type: 'spot' },
  { s: 'NOTUSDT',    mcap: 1200,    type: 'spot' },
  { s: 'THETAUSDT',  mcap: 1800,    type: 'spot' },
  { s: 'CAKEUSDT',   mcap: 1100,    type: 'spot' },
  { s: 'STRKUSDT',   mcap: 1100,    type: 'spot' },
  { s: 'FILUSDT',    mcap: 1900,    type: 'spot' },
  { s: 'RUNEUSDT',   mcap: 1600,    type: 'spot' },
  { s: 'GRTUSDT',    mcap: 1200,    type: 'spot' },
  { s: 'MANAUSDT',   mcap: 1000,    type: 'spot' },
  { s: 'SEIUSDT',    mcap: 1600,    type: 'spot' },
  { s: 'CRVUSDT',    mcap: 990,     type: 'spot' },
  { s: 'PYTHUSDT',   mcap: 870,     type: 'spot' },
  { s: 'WUSDT',      mcap: 950,     type: 'spot' },
  { s: 'EIGENUSDT',  mcap: 780,     type: 'spot' },
  { s: 'FLOWUSDT',   mcap: 900,     type: 'spot' },
  { s: 'DYMUSDT',    mcap: 950,     type: 'spot' },
  { s: 'ALTUSDT',    mcap: 880,     type: 'spot' },
  { s: 'AGIXUSDT',   mcap: 750,     type: 'spot' },
  { s: 'XTZUSDT',    mcap: 800,     type: 'spot' },
  { s: 'NEOUSDT',    mcap: 760,     type: 'spot' },
  { s: 'IOTAUSDT',   mcap: 710,     type: 'spot' },
  { s: 'ZRXUSDT',    mcap: 650,     type: 'spot' },
  { s: 'KSMUSDT',    mcap: 700,     type: 'spot' },
  { s: 'DYDXUSDT',   mcap: 620,     type: 'spot' },
  { s: 'GMXUSDT',    mcap: 580,     type: 'spot' },
  { s: 'CFXUSDT',    mcap: 560,     type: 'spot' },
  { s: 'MINAUSDT',   mcap: 520,     type: 'spot' },
  // SMALL CAP
  { s: 'APEUSDT',    mcap: 690,     type: 'spot' },
  { s: 'GMTUSDT',    mcap: 560,     type: 'spot' },
  { s: 'CELOUSDT',   mcap: 550,     type: 'spot' },
  { s: 'ENJUSDT',    mcap: 590,     type: 'spot' },
  { s: 'COMPUSDT',   mcap: 540,     type: 'spot' },
  { s: 'SNXUSDT',    mcap: 390,     type: 'spot' },
  { s: 'CHZUSDT',    mcap: 740,     type: 'spot' },
  { s: 'ONEUSDT',    mcap: 310,     type: 'spot' },
  { s: 'ZILUSDT',    mcap: 420,     type: 'spot' },
  { s: 'HOTUSDT',    mcap: 430,     type: 'spot' },
  { s: 'ETHFIUSDT',  mcap: 310,     type: 'spot' },
  { s: 'BATUSDT',    mcap: 380,     type: 'spot' },
  { s: 'STORJUSDT',  mcap: 280,     type: 'spot' },
  { s: 'SKLUSDT',    mcap: 260,     type: 'spot' },
  { s: 'ANKRUSDT',   mcap: 240,     type: 'spot' },
  { s: 'WAVESUSDT',  mcap: 480,     type: 'spot' },
  { s: 'ZECUSDT',    mcap: 540,     type: 'spot' },
  { s: 'DASHUSDT',   mcap: 390,     type: 'spot' },
  { s: 'CELRUSDT',   mcap: 220,     type: 'spot' },
  { s: 'HIGHUSDT',   mcap: 210,     type: 'spot' },
  { s: 'JSTUSDT',    mcap: 195,     type: 'spot' },
  { s: 'IOSTUSDT',   mcap: 320,     type: 'spot' },
  { s: 'ONTUSDT',    mcap: 290,     type: 'spot' },
  { s: 'JASMYUSDT',  mcap: 680,     type: 'spot' },
  // MICRO CAP
  { s: 'NEIROUSDT',  mcap: 180,     type: 'spot' },
  { s: 'MEWUSDT',    mcap: 160,     type: 'spot' },
  { s: 'BOMEUSDT',   mcap: 140,     type: 'spot' },
  { s: 'POPCATUSDT', mcap: 190,     type: 'spot' },
  { s: 'GOATUSDT',   mcap: 120,     type: 'spot' },
  { s: 'PNUTUSDT',   mcap: 130,     type: 'spot' },
  { s: 'TURBOUSDT',  mcap: 85,      type: 'spot' },
  { s: 'ACTUSDT',    mcap: 95,      type: 'spot' },
  { s: 'PIXELUSDT',  mcap: 110,     type: 'spot' },
  { s: 'PORTALUSDT', mcap: 90,      type: 'spot' },
  // FUTURES PERPETUAL
  { s: 'BTCUSDT',    mcap: 1300000, type: 'futures', label: 'BTC PERP' },
  { s: 'ETHUSDT',    mcap: 420000,  type: 'futures', label: 'ETH PERP' },
  { s: 'SOLUSDT',    mcap: 75000,   type: 'futures', label: 'SOL PERP' },
  { s: 'BNBUSDT',    mcap: 89000,   type: 'futures', label: 'BNB PERP' },
  { s: 'XRPUSDT',    mcap: 32000,   type: 'futures', label: 'XRP PERP' },
  { s: 'DOGEUSDT',   mcap: 26000,   type: 'futures', label: 'DOGE PERP'},
  { s: 'ADAUSDT',    mcap: 21500,   type: 'futures', label: 'ADA PERP' },
  { s: 'AVAXUSDT',   mcap: 17000,   type: 'futures', label: 'AVAX PERP'},
  { s: 'LINKUSDT',   mcap: 11000,   type: 'futures', label: 'LINK PERP'},
  { s: 'DOTUSDT',    mcap: 12000,   type: 'futures', label: 'DOT PERP' },
  { s: 'LTCUSDT',    mcap: 7300,    type: 'futures', label: 'LTC PERP' },
  { s: 'NEARUSDT',   mcap: 8100,    type: 'futures', label: 'NEAR PERP'},
  { s: 'INJUSDT',    mcap: 3600,    type: 'futures', label: 'INJ PERP' },
  { s: 'SUIUSDT',    mcap: 4800,    type: 'futures', label: 'SUI PERP' },
  { s: 'APTUSDT',    mcap: 6200,    type: 'futures', label: 'APT PERP' },
  { s: 'ARBUSDT',    mcap: 5900,    type: 'futures', label: 'ARB PERP' },
  { s: 'OPUSDT',     mcap: 3200,    type: 'futures', label: 'OP PERP'  },
  { s: 'ATOMUSDT',   mcap: 2400,    type: 'futures', label: 'ATOM PERP'},
  { s: 'FTMUSDT',    mcap: 2300,    type: 'futures', label: 'FTM PERP' },
  { s: 'AAVEUSDT',   mcap: 2700,    type: 'futures', label: 'AAVE PERP'},
  { s: 'XLMUSDT',    mcap: 9800,    type: 'futures', label: 'XLM PERP' },
  { s: 'BCHUSDT',    mcap: 7100,    type: 'futures', label: 'BCH PERP' },
  { s: 'ETCUSDT',    mcap: 4100,    type: 'futures', label: 'ETC PERP' },
  { s: 'PEPEUSDT',   mcap: 5400,    type: 'futures', label: 'PEPE PERP'},
  { s: 'WIFUSDT',    mcap: 3800,    type: 'futures', label: 'WIF PERP' },
  { s: 'SHIBUSDT',   mcap: 9700,    type: 'futures', label: 'SHIB PERP'},
  { s: 'TAOUSDT',    mcap: 3200,    type: 'futures', label: 'TAO PERP' },
  { s: 'WLDUSDT',    mcap: 2100,    type: 'futures', label: 'WLD PERP' },
  { s: 'BONKUSDT',   mcap: 2100,    type: 'futures', label: 'BONK PERP'},
  { s: 'TIAUSDT',    mcap: 2100,    type: 'futures', label: 'TIA PERP' },
  { s: 'KASUSDT',    mcap: 2800,    type: 'futures', label: 'KAS PERP' },
  { s: 'ORDIUSDT',   mcap: 1800,    type: 'futures', label: 'ORDI PERP'},
  { s: 'STXUSDT',    mcap: 3100,    type: 'futures', label: 'STX PERP' },
  { s: 'RUNEUSDT',   mcap: 1600,    type: 'futures', label: 'RUNE PERP'},
  { s: 'ARUSDT',     mcap: 1600,    type: 'futures', label: 'AR PERP'  },
]

export const MCAP_RANGES = {
  all:     [0,       9e9  ],
  large:   [5000,    9e9  ],
  mid:     [500,     5000 ],
  small:   [100,     500  ],
  micro:   [0,       100  ],
}

export const VOL_MIN = {
  any:    0,
  '10m':  10,
  '25m':  25,
  '50m':  50,
  '100m': 100,
  '500m': 500,
}
